import React from 'react';
import ReactDOM from 'react-dom/client';
import './storage.js'; // sets up window.storage BEFORE App mounts
import './index.css';
import App from './App.jsx';

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

// Register the PWA service worker (generated by vite-plugin-pwa at build time)
if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    navigator.serviceWorker.getRegistrations().then(() => {
      import('virtual:pwa-register').then(({ registerSW }) => {
        registerSW({ immediate: true });
      }).catch(() => {
        // vite-plugin-pwa virtual module only exists in a built/dev PWA context
      });
    });
  });
}
